package com.vairapido.api.entity.enums;

public enum WhatsappConversationStep {
    START,
    PASSENGER_IDENTIFICATION,
    ASKING_FULL_NAME,
    ASKING_DOCUMENT,
    CHOOSING_ORIGIN,
    CHOOSING_DESTINATION,
    CHOOSING_DATE,
    CHOOSING_TRIP,
    CHOOSING_SEAT,
    CONFIRMING_BOOKING,
    WAITING_PAYMENT,
    TICKET_ISSUED,
    BOARDING_VALIDATION,
    COMPANY_DASHBOARD,
    FINISHED
}