
package com.secretariapay.api.service.core;

import com.secretariapay.api.entity.core.*;
import com.secretariapay.api.repository.core.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@Service
public class CoreFinanceOperationsService {
 private final SupportTicketRepository tickets; private final SupportTicketMessageRepository ticketMessages; private final FinancialNegotiationRepository negotiations; private final FinancialNegotiationInstallmentRepository installments; private final PaymentMethodConfigRepository methods; private final BankAccountConfigRepository banks; private final BillingRuleRepository rules;
 public CoreFinanceOperationsService(SupportTicketRepository tickets, SupportTicketMessageRepository ticketMessages, FinancialNegotiationRepository negotiations, FinancialNegotiationInstallmentRepository installments, PaymentMethodConfigRepository methods, BankAccountConfigRepository banks, BillingRuleRepository rules){this.tickets=tickets;this.ticketMessages=ticketMessages;this.negotiations=negotiations;this.installments=installments;this.methods=methods;this.banks=banks;this.rules=rules;}
 @Transactional public Map<String,Object> createTicket(Map<String,Object> r){SupportTicket t=new SupportTicket().setProtocolCode("ATD-"+System.currentTimeMillis()).setStudentId(uuid(r.get("studentId"))).setStudentName(str(r,"studentName","Estudante não informado")).setStudentNumber(str(r,"studentNumber",null)).setRequesterPhone(str(r,"requesterPhone",null)).setSubject(str(r,"subject","Atendimento SecretáriaPay")).setReason(str(r,"reason","OUTRO")).setDescription(str(r,"description",null)).setPriority(str(r,"priority","NORMAL")); t=tickets.save(t); if(r.get("message")!=null) ticketMessages.save(new SupportTicketMessage().setTicket(t).setSenderType(str(r,"senderType","STUDENT")).setSenderName(str(r,"senderName",t.getStudentName())).setMessage(str(r,"message","Solicitação aberta."))); return ticket(t);}
 @Transactional public Map<String,Object> updateTicket(UUID id, String status, Map<String,Object> r){SupportTicket t=tickets.findById(id).orElseThrow(); t.setStatus(status); if("CLOSED".equalsIgnoreCase(status))t.setClosedAt(LocalDateTime.now()); if(r!=null&&r.get("assignedTo")!=null)t.setAssignedTo(str(r,"assignedTo",null)); return ticket(tickets.save(t));}
 @Transactional public Map<String,Object> addMessage(UUID id, Map<String,Object> r){SupportTicket t=tickets.findById(id).orElseThrow(); SupportTicketMessage m=ticketMessages.save(new SupportTicketMessage().setTicket(t).setSenderType(str(r,"senderType","STAFF")).setSenderName(str(r,"senderName",null)).setMessage(str(r,"message",""))); return msg(m);}
 @Transactional public Map<String,Object> createNegotiation(Map<String,Object> r){FinancialNegotiation n=new FinancialNegotiation().setNegotiationCode("NEG-"+System.currentTimeMillis()).setStudentId(uuid(r.get("studentId"))).setStudentName(str(r,"studentName",null)).setStudentNumber(str(r,"studentNumber",null)).setChargeId(uuid(r.get("chargeId"))).setChargeCode(str(r,"chargeCode",null)).setTotalAmount(decimal(r.get("totalAmount"),BigDecimal.ZERO)).setCurrency(str(r,"currency","AOA")).setProposalType(str(r,"proposalType","INSTALLMENT")).setInstallments(integer(r.get("installments"),1)).setFirstDueDate(date(r.get("firstDueDate"))).setRequestNote(str(r,"requestNote",null)); n=negotiations.save(n); createInstallments(n); return negotiation(n);}
 private void createInstallments(FinancialNegotiation n){int qtd=Math.max(1,n.getInstallments()); BigDecimal amount=n.getTotalAmount()==null?BigDecimal.ZERO:n.getTotalAmount(); BigDecimal each=amount.divide(BigDecimal.valueOf(qtd),2,java.math.RoundingMode.HALF_UP); LocalDate first=n.getFirstDueDate()==null?LocalDate.now().plusDays(7):n.getFirstDueDate(); for(int i=1;i<=qtd;i++){installments.save(new FinancialNegotiationInstallment().setNegotiation(n).setInstallmentNumber(i).setAmount(each).setCurrency(n.getCurrency()).setDueDate(first.plusMonths(i-1)));}}
 @Transactional public Map<String,Object> reviewNegotiation(UUID id, String status, Map<String,Object> r){FinancialNegotiation n=negotiations.findById(id).orElseThrow(); n.setStatus(status).setReviewedAt(LocalDateTime.now()).setReviewNote(str(r,"reviewNote",null)); return negotiation(negotiations.save(n));}
 @Transactional public Map<String,Object> createMethod(Map<String,Object> r){PaymentMethodConfig m=methods.save(new PaymentMethodConfig().setInstitutionId(uuid(r.get("institutionId"))).setMethodCode(str(r,"methodCode","METHOD_"+System.currentTimeMillis())).setMethodName(str(r,"methodName","Método de pagamento")).setDescription(str(r,"description",null)).setInstructions(str(r,"instructions",null)).setActive(bool(r.get("active"),true)));return method(m);} 
 @Transactional public Map<String,Object> createBank(Map<String,Object> r){BankAccountConfig b=banks.save(new BankAccountConfig().setInstitutionId(uuid(r.get("institutionId"))).setHolderName(str(r,"holderName","OMNEN INTELENGENDA")).setBankName(str(r,"bankName","Banco Angolano de Investimento")).setAccountNumber(str(r,"accountNumber",null)).setIban(str(r,"iban",null)).setCurrency(str(r,"currency","AOA")).setNotes(str(r,"notes",null)).setActive(bool(r.get("active"),true)));return bank(b);} 
 @Transactional public Map<String,Object> createRule(Map<String,Object> r){BillingRule br=rules.save(new BillingRule().setInstitutionId(uuid(r.get("institutionId"))).setRuleName(str(r,"ruleName","Regra de propina")).setChargeType(str(r,"chargeType","PROPINA")).setDueDay(integer(r.get("dueDay"),10)).setGraceDays(integer(r.get("graceDays"),0)).setFineType(str(r,"fineType","NONE")).setFineValue(decimal(r.get("fineValue"),BigDecimal.ZERO)).setInterestType(str(r,"interestType","NONE")).setDailyInterestValue(decimal(r.get("dailyInterestValue"),BigDecimal.ZERO)).setDiscountType(str(r,"discountType","NONE")).setDiscountValue(decimal(r.get("discountValue"),BigDecimal.ZERO)).setActive(bool(r.get("active"),true)));return rule(br);} 
 public List<Map<String,Object>> tickets(){return tickets.findAll().stream().map(this::ticket).toList();} public List<Map<String,Object>> negotiations(){return negotiations.findAll().stream().map(this::negotiation).toList();} public List<Map<String,Object>> methods(){return methods.findAll().stream().map(this::method).toList();} public List<Map<String,Object>> banks(){return banks.findAll().stream().map(this::bank).toList();} public List<Map<String,Object>> rules(){return rules.findAll().stream().map(this::rule).toList();}
 public Map<String,Object> ticket(SupportTicket t){return map("id",t.getId(),"protocolCode",t.getProtocolCode(),"studentId",t.getStudentId(),"studentName",t.getStudentName(),"studentNumber",t.getStudentNumber(),"requesterPhone",t.getRequesterPhone(),"subject",t.getSubject(),"reason",t.getReason(),"description",t.getDescription(),"priority",t.getPriority(),"status",t.getStatus(),"assignedTo",t.getAssignedTo(),"createdAt",t.getCreatedAt(),"updatedAt",t.getUpdatedAt(),"closedAt",t.getClosedAt());}
 public Map<String,Object> msg(SupportTicketMessage m){return map("id",m.getId(),"senderType",m.getSenderType(),"senderName",m.getSenderName(),"message",m.getMessage(),"createdAt",m.getCreatedAt());}
 public Map<String,Object> negotiation(FinancialNegotiation n){return map("id",n.getId(),"negotiationCode",n.getNegotiationCode(),"studentId",n.getStudentId(),"studentName",n.getStudentName(),"studentNumber",n.getStudentNumber(),"chargeId",n.getChargeId(),"chargeCode",n.getChargeCode(),"totalAmount",n.getTotalAmount(),"currency",n.getCurrency(),"proposalType",n.getProposalType(),"installments",n.getInstallments(),"firstDueDate",n.getFirstDueDate(),"status",n.getStatus(),"requestNote",n.getRequestNote(),"reviewNote",n.getReviewNote(),"reviewedAt",n.getReviewedAt(),"createdAt",n.getCreatedAt(),"updatedAt",n.getUpdatedAt());}
 public Map<String,Object> method(PaymentMethodConfig m){return map("id",m.getId(),"institutionId",m.getInstitutionId(),"methodCode",m.getMethodCode(),"methodName",m.getMethodName(),"description",m.getDescription(),"instructions",m.getInstructions(),"active",m.getActive(),"createdAt",m.getCreatedAt(),"updatedAt",m.getUpdatedAt());}
 public Map<String,Object> bank(BankAccountConfig b){return map("id",b.getId(),"institutionId",b.getInstitutionId(),"holderName",b.getHolderName(),"bankName",b.getBankName(),"accountNumber",b.getAccountNumber(),"iban",b.getIban(),"currency",b.getCurrency(),"active",b.getActive(),"notes",b.getNotes(),"createdAt",b.getCreatedAt(),"updatedAt",b.getUpdatedAt());}
 public Map<String,Object> rule(BillingRule b){return map("id",b.getId(),"institutionId",b.getInstitutionId(),"ruleName",b.getRuleName(),"chargeType",b.getChargeType(),"dueDay",b.getDueDay(),"graceDays",b.getGraceDays(),"fineType",b.getFineType(),"fineValue",b.getFineValue(),"interestType",b.getInterestType(),"dailyInterestValue",b.getDailyInterestValue(),"discountType",b.getDiscountType(),"discountValue",b.getDiscountValue(),"active",b.getActive(),"createdAt",b.getCreatedAt(),"updatedAt",b.getUpdatedAt());}
 private Map<String,Object> map(Object...v){Map<String,Object> m=new LinkedHashMap<>(); for(int i=0;i<v.length;i+=2)m.put(String.valueOf(v[i]),v[i+1]); return m;} private String str(Map<String,Object> m,String k,String d){Object v=m==null?null:m.get(k); return v==null?d:String.valueOf(v);} private UUID uuid(Object v){try{return v==null||String.valueOf(v).isBlank()?null:UUID.fromString(String.valueOf(v));}catch(Exception e){return null;}} private BigDecimal decimal(Object v,BigDecimal d){try{return v==null?d:new BigDecimal(String.valueOf(v));}catch(Exception e){return d;}} private Integer integer(Object v,Integer d){try{return v==null?d:Integer.parseInt(String.valueOf(v));}catch(Exception e){return d;}} private LocalDate date(Object v){try{return v==null||String.valueOf(v).isBlank()?null:LocalDate.parse(String.valueOf(v));}catch(Exception e){return null;}} private Boolean bool(Object v, Boolean d){return v==null?d:Boolean.parseBoolean(String.valueOf(v));}
}
