package secretariapay.api.entity.enums.academic;

public enum AcademicRequestType {
    DECLARACAO_FREQUENCIA, DECLARACAO_MATRICULA, HISTORICO_ACADEMICO, INSCRICAO_EXAME, RENOVACAO_MATRICULA, ATUALIZACAO_DADOS, CALENDARIO_ACADEMICO, SITUACAO_DOCUMENTOS, OUTRO
}
