server:
  port: 8080

spring:
  application:
    name: vairapido-api

  datasource:
    url: jdbc:postgresql://localhost:5432/vairapido_db
    username: vairapido_user
    password: vairapido123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt-secret: "vaiRapidoBackendJwtSecretKeyForDevelopmentOnlyChangeInProduction2026"
    jwt-expiration-minutes: 1440

vairapido:
  business:
    country: ${VAIRAPIDO_BUSINESS_COUNTRY:BR}
    currency: ${VAIRAPIDO_BUSINESS_CURRENCY:BRL}

  whatsapp:
    verify-token: ${VAIRAPIDO_WHATSAPP_VERIFY_TOKEN:vairapido-dev-token}
    enabled: ${VAIRAPIDO_WHATSAPP_ENABLED:false}
    phone-number-id: ${VAIRAPIDO_WHATSAPP_PHONE_NUMBER_ID:}
    access-token: ${VAIRAPIDO_WHATSAPP_ACCESS_TOKEN:}
    graph-api-version: ${VAIRAPIDO_WHATSAPP_GRAPH_API_VERSION:v20.0}
    graph-api-base-url: ${VAIRAPIDO_WHATSAPP_GRAPH_API_BASE_URL:https://graph.facebook.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always