
package com.secretariapay.api.entity.core;

import jakarta.persistence.*;
import java.time.*;
import java.math.BigDecimal;
import java.util.UUID;

@Entity @Table(name="bank_account_configs")
public class BankAccountConfig { @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @Column(name="institution_id") private UUID institutionId; @Column(name="holder_name",nullable=false,length=180) private String holderName; @Column(name="bank_name",nullable=false,length=180) private String bankName; @Column(name="account_number",length=80) private String accountNumber; @Column(length=120) private String iban; @Column(nullable=false,length=10) private String currency="AOA"; @Column(nullable=false) private Boolean active=true; @Column(columnDefinition="text") private String notes; @Column(name="created_at",nullable=false) private LocalDateTime createdAt; @Column(name="updated_at",nullable=false) private LocalDateTime updatedAt; @PrePersist public void prePersist(){LocalDateTime n=LocalDateTime.now();createdAt=n;updatedAt=n;if(active==null)active=true;if(currency==null)currency="AOA";} @PreUpdate public void preUpdate(){updatedAt=LocalDateTime.now();} public UUID getId(){return id;} public UUID getInstitutionId(){return institutionId;} public BankAccountConfig setInstitutionId(UUID v){institutionId=v;return this;} public String getHolderName(){return holderName;} public BankAccountConfig setHolderName(String v){holderName=v;return this;} public String getBankName(){return bankName;} public BankAccountConfig setBankName(String v){bankName=v;return this;} public String getAccountNumber(){return accountNumber;} public BankAccountConfig setAccountNumber(String v){accountNumber=v;return this;} public String getIban(){return iban;} public BankAccountConfig setIban(String v){iban=v;return this;} public String getCurrency(){return currency;} public BankAccountConfig setCurrency(String v){currency=v;return this;} public Boolean getActive(){return active;} public BankAccountConfig setActive(Boolean v){active=v;return this;} public String getNotes(){return notes;} public BankAccountConfig setNotes(String v){notes=v;return this;} public LocalDateTime getCreatedAt(){return createdAt;} public LocalDateTime getUpdatedAt(){return updatedAt;} }
