
package com.secretariapay.api.entity.core;

import jakarta.persistence.*;
import java.time.*;
import java.math.BigDecimal;
import java.util.UUID;

@Entity @Table(name="financial_negotiations")
public class FinancialNegotiation {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @Column(name="negotiation_code",nullable=false,unique=true,length=60) private String negotiationCode;
 @Column(name="student_id") private UUID studentId; @Column(name="student_name",length=180) private String studentName; @Column(name="student_number",length=80) private String studentNumber; @Column(name="charge_id") private UUID chargeId; @Column(name="charge_code",length=80) private String chargeCode;
 @Column(name="total_amount",nullable=false,precision=14,scale=2) private BigDecimal totalAmount=BigDecimal.ZERO; @Column(nullable=false,length=10) private String currency="AOA"; @Column(name="proposal_type",nullable=false,length=40) private String proposalType="INSTALLMENT"; @Column(nullable=false) private Integer installments=1; @Column(name="first_due_date") private LocalDate firstDueDate;
 @Column(nullable=false,length=30) private String status="REQUESTED"; @Column(name="request_note",columnDefinition="text") private String requestNote; @Column(name="review_note",columnDefinition="text") private String reviewNote; @Column(name="created_at",nullable=false) private LocalDateTime createdAt; @Column(name="updated_at",nullable=false) private LocalDateTime updatedAt; @Column(name="reviewed_at") private LocalDateTime reviewedAt;
 @PrePersist public void prePersist(){LocalDateTime n=LocalDateTime.now();createdAt=n;updatedAt=n;if(status==null)status="REQUESTED";if(currency==null)currency="AOA";if(totalAmount==null)totalAmount=BigDecimal.ZERO;if(installments==null||installments<1)installments=1;}
 @PreUpdate public void preUpdate(){updatedAt=LocalDateTime.now();}
 public UUID getId(){return id;} public String getNegotiationCode(){return negotiationCode;} public FinancialNegotiation setNegotiationCode(String v){negotiationCode=v;return this;} public UUID getStudentId(){return studentId;} public FinancialNegotiation setStudentId(UUID v){studentId=v;return this;} public String getStudentName(){return studentName;} public FinancialNegotiation setStudentName(String v){studentName=v;return this;} public String getStudentNumber(){return studentNumber;} public FinancialNegotiation setStudentNumber(String v){studentNumber=v;return this;} public UUID getChargeId(){return chargeId;} public FinancialNegotiation setChargeId(UUID v){chargeId=v;return this;} public String getChargeCode(){return chargeCode;} public FinancialNegotiation setChargeCode(String v){chargeCode=v;return this;} public BigDecimal getTotalAmount(){return totalAmount;} public FinancialNegotiation setTotalAmount(BigDecimal v){totalAmount=v;return this;} public String getCurrency(){return currency;} public FinancialNegotiation setCurrency(String v){currency=v;return this;} public String getProposalType(){return proposalType;} public FinancialNegotiation setProposalType(String v){proposalType=v;return this;} public Integer getInstallments(){return installments;} public FinancialNegotiation setInstallments(Integer v){installments=v;return this;} public LocalDate getFirstDueDate(){return firstDueDate;} public FinancialNegotiation setFirstDueDate(LocalDate v){firstDueDate=v;return this;} public String getStatus(){return status;} public FinancialNegotiation setStatus(String v){status=v;return this;} public String getRequestNote(){return requestNote;} public FinancialNegotiation setRequestNote(String v){requestNote=v;return this;} public String getReviewNote(){return reviewNote;} public FinancialNegotiation setReviewNote(String v){reviewNote=v;return this;} public FinancialNegotiation setReviewedAt(LocalDateTime v){reviewedAt=v;return this;} public LocalDateTime getReviewedAt(){return reviewedAt;} public LocalDateTime getCreatedAt(){return createdAt;} public LocalDateTime getUpdatedAt(){return updatedAt;}
}
