package secretariapay.api.entity.enums.restriction;

public enum AcademicRestrictionType {
    PORTAL_ESTUDANTE, CONSULTA_NOTAS, INSCRICAO_EXAME, RENOVACAO_MATRICULA, EMISSAO_DECLARACAO, EMISSAO_CERTIFICADO, SOLICITACOES_ACADEMICAS, BIBLIOTECA_DIGITAL, SERVICOS_ADMINISTRATIVOS, OUTRO
}
