package com.secretariapay.api.entity.enums;

public enum WhatsappConversationStep {
    START,

    PASSENGER_IDENTIFICATION,
    ASKING_FULL_NAME,
    ASKING_DOCUMENT,
    CONFIRMING_SAVED_PASSENGER,
    CONFIRMING_PASSENGER_DATA,
    CHOOSING_ORIGIN,
    CHOOSING_DESTINATION,
    CHOOSING_DATE,
    CHOOSING_TRIP,
    CHOOSING_SEAT,
    CONFIRMING_BOOKING,
    WAITING_PAYMENT,
    TICKET_ISSUED,
    BOARDING_VALIDATION,
    COMPANY_DASHBOARD,
    FINISHED,

    SECRETARIAPAY_START,
    SECRETARIAPAY_WAITING_IDENTIFIER,
    SECRETARIAPAY_STUDENT_FOUND,
    SECRETARIAPAY_CHARGE_FOUND,
    SECRETARIAPAY_WAITING_PAYMENT_PROOF,
    SECRETARIAPAY_WAITING_HUMAN_SUPPORT,
    SECRETARIAPAY_FINISHED
}