package com.secretariapay.api.entity.enums;

public enum WhatsappConversationStep {
    SECRETARIAPAY_START,
    SECRETARIAPAY_WAITING_IDENTIFIER,
    SECRETARIAPAY_STUDENT_FOUND,
    SECRETARIAPAY_CHARGE_FOUND,
    SECRETARIAPAY_WAITING_PAYMENT_PROOF,
    SECRETARIAPAY_WAITING_HUMAN_SUPPORT,
    SECRETARIAPAY_FINISHED
}
