create table if not exists institution_dcr_policies (
    id uuid primary key,
    institution_id uuid not null,
    policy_code varchar(100) not null unique,
    policy_name varchar(180) not null,
    currency varchar(10) not null default 'AOA',
    payment_window_start_day integer not null default 3,
    no_penalty_until_day integer not null default 10,
    first_penalty_start_day integer not null default 11,
    first_penalty_percent numeric(8,2) not null default 20.00,
    second_penalty_start_day integer not null default 15,
    second_penalty_percent numeric(8,2) not null default 30.00,
    daily_interest_enabled boolean not null default false,
    daily_interest_percent numeric(8,4) not null default 0.0000,
    debt_after_days integer not null default 30,
    delinquency_after_days integer not null default 90,
    pre_due_reminder_days integer not null default 5,
    compulsory_reminder_start_day integer not null default 22,
    whatsapp_allowed_start time not null default '07:00:00',
    whatsapp_allowed_end time not null default '19:00:00',
    provisional_automatic_confirmation boolean not null default true,
    manual_dcr_confirmation_required boolean not null default true,
    dcr_approval_role varchar(80) not null default 'DCR_COORDENACAO',
    official_email varchar(180),
    cc_email varchar(180),
    active boolean not null default true,
    notes text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index if not exists idx_institution_dcr_policies_institution on institution_dcr_policies(institution_id);
create index if not exists idx_institution_dcr_policies_active on institution_dcr_policies(active);
create index if not exists idx_institution_dcr_policies_code on institution_dcr_policies(policy_code);

insert into institution_dcr_policies (
    id,
    institution_id,
    policy_code,
    policy_name,
    currency,
    payment_window_start_day,
    no_penalty_until_day,
    first_penalty_start_day,
    first_penalty_percent,
    second_penalty_start_day,
    second_penalty_percent,
    daily_interest_enabled,
    daily_interest_percent,
    debt_after_days,
    delinquency_after_days,
    pre_due_reminder_days,
    compulsory_reminder_start_day,
    whatsapp_allowed_start,
    whatsapp_allowed_end,
    provisional_automatic_confirmation,
    manual_dcr_confirmation_required,
    dcr_approval_role,
    official_email,
    cc_email,
    active,
    notes,
    created_at,
    updated_at
) values (
    '24dc0000-0000-4000-8000-000000000001',
    'c3726494-46b5-4563-8e84-0a04334fac8c',
    'IMETRO_DCR_2026',
    'Política DCR IMETRO - propinas, dívida e inadimplência',
    'AOA',
    3,
    10,
    11,
    20.00,
    15,
    30.00,
    false,
    0.0000,
    30,
    90,
    5,
    22,
    '07:00:00',
    '19:00:00',
    true,
    true,
    'DCR_COORDENACAO',
    'dcr_pay@imetroangola.com',
    'df.oi_pay@imetroangola.com',
    true,
    'Regras levantadas com o cliente IMETRO: pagamento sem multa até dia 10; multa de 20% depois do dia 10; multa de 30% depois do dia 15; sem juros diário; dívida após 30 dias; inadimplência após 90 dias; mensagens apenas das 07h às 19h; pagamento automático apenas provisório e confirmação manual obrigatória pela DCR.',
    now(),
    now()
)
on conflict (policy_code) do update set
    policy_name = excluded.policy_name,
    currency = excluded.currency,
    payment_window_start_day = excluded.payment_window_start_day,
    no_penalty_until_day = excluded.no_penalty_until_day,
    first_penalty_start_day = excluded.first_penalty_start_day,
    first_penalty_percent = excluded.first_penalty_percent,
    second_penalty_start_day = excluded.second_penalty_start_day,
    second_penalty_percent = excluded.second_penalty_percent,
    daily_interest_enabled = excluded.daily_interest_enabled,
    daily_interest_percent = excluded.daily_interest_percent,
    debt_after_days = excluded.debt_after_days,
    delinquency_after_days = excluded.delinquency_after_days,
    pre_due_reminder_days = excluded.pre_due_reminder_days,
    compulsory_reminder_start_day = excluded.compulsory_reminder_start_day,
    whatsapp_allowed_start = excluded.whatsapp_allowed_start,
    whatsapp_allowed_end = excluded.whatsapp_allowed_end,
    provisional_automatic_confirmation = excluded.provisional_automatic_confirmation,
    manual_dcr_confirmation_required = excluded.manual_dcr_confirmation_required,
    dcr_approval_role = excluded.dcr_approval_role,
    official_email = excluded.official_email,
    cc_email = excluded.cc_email,
    active = excluded.active,
    notes = excluded.notes,
    updated_at = now();
